version: 0.2
phases:
  build:
    commands:
      - echo "login to codeartifact"
      - npm install
      - aws codeartifact login --tool npm --repository serverless --domain quotable-value --domain-owner 948396734470 --region ap-southeast-2
      - npm publish
      - echo "publishing to codeartifact completed"
