version: 0.2
phases:
  build:
    commands:
      - echo "login to codeartifact"
      - npm install
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain quotable-value --domain-owner 948396734470 --region ap-southeast-2 --query authorizationToken --output text`
      - npm publish
      - echo "publishing to codeartifact completed"
